name=Multifunction_Button
version=2.1.2
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=A robust  and versatile library for handling single clicks, multi-clicks, long presses, repeat actions, and toggle switches safely.
paragraph=This library provides a state-machine based approach to read buttons without blocking the loop. It solves common hardware button issues like debouncing and state conflicts, allowing you to seamlessly detect double-clicks, triple-clicks, long holds, and act as a toggle switch concurrently without race conditions.
category=Signal Input/Output
url=https://github.com/0ADILL3/Multifunction_Button
architectures=*
includes=Multifunction_Button.h