name=Multifunction_Button
version=1.0.0
author=Ade Firman
maintainer=Ade Firman <adilllfirman@gmail.com>
sentence=A simple and versatile library for handling button presses, long presses, multi-clicks, and repeat actions.
paragraph=This library allows you to easily handle various button events such as single click, multiple clicks, long press (hold), release, and repeating actions while the button is held down. It includes built-in debouncing.
category=Signal Input/Output
url=https://github.com/0ADILL3/Multifunction_Button
architectures=*
includes=Multifunction_Button.h